<a href="https://colab.research.google.com/github/SaiKarthik29/ML_23AG1A66I2/blob/main/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
list=[1,2,3,4]
arr1=np.array(list)
print(arr1)

[1 2 3 4]


In [3]:
arr1=np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


In [4]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [9]:
arr3=np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [11]:
print(arr1.dtype)

int64


In [13]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [14]:
print(arr1.size)
print(arr2.size)
print(arr3.size)

4
6
12


In [15]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(4,)
(2, 3)
(2, 2, 3)


In [17]:
print(arr1.itemsize)
arr4=np.array([10,20,30],dtype=np.int32)
print(arr4.itemsize)

8
4


In [19]:
print(arr1.data)
print(arr2.data)
print(arr3.data)

In [26]:
print(arr1[0])
print(arr1[1])
print(arr1[2])
print(arr1[3])

1
2
3
4


In [27]:
arr1[0]=10
print(arr1)

[10  2  3  4]


In [29]:
print(arr2[0,1])
print(arr2[1,2])

2
6
